### ISSUE TITLE
Getting the below error while trying to run

### ISSUE THREAD

**Issue by vivek721** [gnzeleven/CovidCases-MapReduce#1]
value asScala is not a member of Iterable[org.apache.hadoop.io.IntWritable]
      var sum = values.asScala.foldLeft(0)(_ + _.get)

**Comment by gnzeleven** [comment]
Hi Vivek, thank you for raising this issue. I think this issue could be because assembly.sbt file is not configured properly. Create a file - assembly.sbt in Project folder(the file has to be in the same level as build.properties). Type the following: "addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "1.1.0")" and then try "sbt clean compile assembly".

**Comment by karanmalh0tra** [comment]
Hi @gnzeleven ,
in the .gitignore, you can have
_project/project
project/target_
instead of ignoring the entire project directory. 
Would help combatting issues like these.
